# Generated by Django 4.2.7 on 2025-10-26 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScamDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company_identifier",
                    models.CharField(
                        blank=True,
                        help_text="CIK or ticker symbol",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("jurisdiction", models.CharField(default="US", max_length=50)),
                (
                    "overall_risk_score",
                    models.FloatField(
                        default=0.0, help_text="Overall risk score (0-1)"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "category_scores",
                    models.JSONField(default=dict, help_text="Risk scores by category"),
                ),
                (
                    "red_flags",
                    models.JSONField(
                        default=list, help_text="List of red flags identified"
                    ),
                ),
                (
                    "green_flags",
                    models.JSONField(
                        default=list, help_text="List of positive indicators"
                    ),
                ),
                (
                    "detailed_findings",
                    models.JSONField(
                        default=dict, help_text="Detailed findings by category"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(default=list, help_text="Recommended actions"),
                ),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scam_detections",
                        to="backend.merchant",
                    ),
                ),
            ],
            options={
                "ordering": ["-analysis_date"],
                "indexes": [
                    models.Index(
                        fields=["company_name"], name="backend_sca_company_6e6ba1_idx"
                    ),
                    models.Index(
                        fields=["risk_level"], name="backend_sca_risk_le_6c16fe_idx"
                    ),
                    models.Index(
                        fields=["-analysis_date"], name="backend_sca_analysi_0de996_idx"
                    ),
                ],
            },
        ),
    ]
